### ISSUE TITLE
Seg. Fault in Visualization mode

### ISSUE THREAD

**Issue by rakithab** [JeffersonLab/remoll#482]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): Develop
- revision (HEAD for most recent): 
- OS or system: Ubuntu 20.04.2 LTS
- Special ROOT or Geant4 versions? geant4.10.07.p01 and root_v6.22.08

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. ./build/remoll
2. /control/execute macros/vis.mac

### Expected Result: (what do you expect when you execute the steps above)
Geometry visualization must be displayed

### Actual Result: (what do you get when you execute the steps above)
Seg. Fault

[log.txt](https://github.com/JeffersonLab/remoll/files/6387724/log.txt)

**Comment by rakithab** [comment]
`cde@cde-Latitude-E7250:~/mlrcd$ ./build/remoll

**************************************************************
 Geant4 version Name: geant4-10-07-patch-01    (5-February-2021)
                       Copyright : Geant4 Collaboration
                      References : NIM A 506 (2003), 250-303
                                 : IEEE-TNS 53 (2006), 270-278
                                 : NIM A 835 (2016), 186-225
                             WWW : http://geant4.org/
**************************************************************

remoll: Since the high precision neutron simulation in the some physics lists  
remoll: generates a lot of warnings that cannot be avoided, we are setting the 
remoll: physics list verbose level to zero. Use /remoll/physlist/verbose to set
remoll: the verbose level to a non-zero value.

You are setting a new verbose level for Particle HP package.
the new value will be used in whole of the Particle HP package, i.e., models and cross sections for Capture, Elastic, Fission and Inelastic interaction.

<<< Geant4 Physics List simulation engine: QGSP_BERT

<<< Reference Physics List QGSP_BERT is built

remoll: loaded reference physics list QGSP_BERT
Optical physics not active
remoll: step limiter physics is enabled
remoll: parallel physics is enabled
remoll: optical physics is disabled
remoll: All possible event generators are instantiated every time.
remoll: This means some will not find necessary input files or
remoll: print other information in the next few lines.
File name read as remollGenFunctions.root
Function name read as elastic_0
Setting the external file to remollGenFunctions.root
Error in <TFile::TFile>: file remollGenFunctions.root does not exist
could not find function in file remollGenFunctions.root
Setting generator to moller
Available UI session types: [ Qt, GAG, tcsh, csh ]

remoll: Note: GDML file validation can cause many warnings.
remoll: Some can be safely ignore. Here are some guidelines:
remoll: - 'ID attribute is referenced but was never declared'
remoll:   If the attribute starts with G4_ it is likely defined
remoll:   in the NIST materials database and declared later.
remoll: - 'attribute phi is not declared for element direction'
remoll:   Replication along the phi direction is not supported
remoll:   by the GDML standard, but it is by geant4.
remoll: - 'no declaration found for element property'
remoll:   Setting optical properties is not supported
remoll:   by the GDML standard, but it is by geant4 (e.g. G01).

Reading mollerMother_merged.gdml
- schema validation off
- overlap check off

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 9 (Thread 0x7f04450a0700 (LWP 4221)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x560c588798c8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x560c58879878, cond=0x560c588798a0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x560c588798a0, mutex=0x560c58879878) at pthread_cond_wait.c:638
#3  0x00007f0446d5eb5b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f0446d5e75b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f046fc99609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f04731c4293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 8 (Thread 0x7f04458a1700 (LWP 4220)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x560c588798c8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x560c58879878, cond=0x560c588798a0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x560c588798a0, mutex=0x560c58879878) at pthread_cond_wait.c:638
#3  0x00007f0446d5eb5b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f0446d5e75b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f046fc99609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f04731c4293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 7 (Thread 0x7f04460a2700 (LWP 4219)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x560c588798c8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x560c58879878, cond=0x560c588798a0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x560c588798a0, mutex=0x560c58879878) at pthread_cond_wait.c:638
#3  0x00007f0446d5eb5b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f0446d5e75b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f046fc99609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f04731c4293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7f04468a3700 (LWP 4218)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x560c588798c8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x560c58879878, cond=0x560c588798a0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x560c588798a0, mutex=0x560c58879878) at pthread_cond_wait.c:638
#3  0x00007f0446d5eb5b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007f0446d5e75b in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007f046fc99609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f04731c4293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7f0455132700 (LWP 4216)):
#0  0x00007f04731b7aff in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f046d2b336e in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f046d2b34a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f046e9e7565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f046e98e4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f046e7c6785 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f0458615efa in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007f046e7c79d2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f046fc99609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f04731c4293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7f04559e1700 (LWP 4215)):
#0  0x00007f04731b7aff in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f046d2b336e in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f046d2b36f3 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f0456762f8a in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f046d2dcad1 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f046fc99609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f04731c4293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7f04561e2700 (LWP 4214)):
#0  0x00007f04731b7aff in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f046d2b336e in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f046d2b34a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f046d2b34f1 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f046d2dcad1 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f046fc99609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f04731c4293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f0457d1b700 (LWP 4213)):
#0  0x00007f04731b7aff in poll () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f046db08c1a in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f046db0a90a in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f0458759298 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f046e7c79d2 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f046fc99609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f04731c4293 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f046a5781c0 (LWP 4196)):
#0  0x00007f0473187dff in wait4 () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f04730f70e7 in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f047420089e in TUnixSystem::StackTrace() () from /home/cde/root/root/lib/libCore.so.6.22
#3  0x00007f04741fd725 in TUnixSystem::DispatchSignals(ESignals) () from /home/cde/root/root/lib/libCore.so.6.22
#4  <signal handler called>
#5  0x00007f0473aacab5 in G4UIQt::ReceiveG4cout(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#6  0x00007f0473571782 in G4coutDestination::ReceiveG4cout_(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4global.so
#7  0x00007f0473607651 in G4strstreambuf::sync() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#8  0x00007f04733e3a43 in std::ostream::flush() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f04730146ff in G4GDMLRead::Read(G4String const&, bool, bool, bool) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4persistency.so
#10 0x00007f0474460090 in G4GDMLParser::Read (validate=<optimized out>, filename=..., this=0x560c582bb290) at /home/cde/geant4/geant4.10.07.p01-install/include/Geant4/G4GDMLParser.icc:35
#11 G4GDMLParser::Read (validate=<optimized out>, filename=..., this=0x560c582bb290) at /home/cde/geant4/geant4.10.07.p01-install/include/Geant4/G4GDMLParser.icc:31
#12 remollDetectorConstruction::ParseGDMLFile (this=0x560c582bb160) at /home/cde/mlrcd/src/remollDetectorConstruction.cc:544
#13 0x00007f0474460e85 in remollDetectorConstruction::Construct (this=0x560c582bb160) at /home/cde/mlrcd/src/remollDetectorConstruction.cc:912
#14 0x00007f047366653e in G4RunManager::InitializeGeometry() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#15 0x00007f04736662e4 in G4RunManager::Initialize() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#16 0x00007f047368420d in G4RunMessenger::SetNewValue(G4UIcommand*, G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#17 0x00007f04735e335f in G4UIcommand::DoIt(G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#18 0x00007f0473600c9a in G4UImanager::ApplyCommand(char const*) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#19 0x00007f04735d1251 in G4UIbatch::ExecCommand(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#20 0x00007f04735d3206 in G4UIbatch::SessionStart() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#21 0x00007f0473602400 in G4UImanager::ExecuteMacroFile(char const*) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#22 0x00007f04735eed6d in G4UIcontrolMessenger::SetNewValue(G4UIcommand*, G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#23 0x00007f04735e335f in G4UIcommand::DoIt(G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#24 0x00007f0473600c9a in G4UImanager::ApplyCommand(char const*) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#25 0x00007f0473abb89f in G4VBasicShell::ExecuteCommand(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#26 0x00007f0473ac0ade in G4VBasicShell::ApplyShellCommand(G4String const&, bool&, bool&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#27 0x00007f0473ab08ae in G4UIQt::CommandEnteredCallback() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#28 0x00007f046e9bb300 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007f046f64d4a9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007f046e9bb300 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007f046f653c85 in QWidgetLineControl::processKeyEvent(QKeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007f046f64699f in QLineEdit::keyPressEvent(QKeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007f046f54377d in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007f046f64cd32 in QLineEdit::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007f046f500a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007f046f50a81e in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007f046e98f93a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007f046f562216 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007f046f500a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007f046f50a0f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007f046e98f93a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007f046ed74b2b in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#43 0x00007f046ed7a0f1 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#44 0x00007f046ed5435b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#45 0x00007f045875a32e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#46 0x00007f046d2b317d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007f046d2b3400 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007f046d2b34a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007f046e9e7565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#50 0x00007f046e98e4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007f046e996246 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007f0473aac28d in G4UIQt::SessionStart() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#53 0x0000560c54ae550a in main (argc=1, argv=0x7ffe53039a38) at /home/cde/mlrcd/remoll.cc:162
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum https://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f0473aacab5 in G4UIQt::ReceiveG4cout(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#6  0x00007f0473571782 in G4coutDestination::ReceiveG4cout_(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4global.so
#7  0x00007f0473607651 in G4strstreambuf::sync() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#8  0x00007f04733e3a43 in std::ostream::flush() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f04730146ff in G4GDMLRead::Read(G4String const&, bool, bool, bool) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4persistency.so
#10 0x00007f0474460090 in G4GDMLParser::Read (validate=<optimized out>, filename=..., this=0x560c582bb290) at /home/cde/geant4/geant4.10.07.p01-install/include/Geant4/G4GDMLParser.icc:35
#11 G4GDMLParser::Read (validate=<optimized out>, filename=..., this=0x560c582bb290) at /home/cde/geant4/geant4.10.07.p01-install/include/Geant4/G4GDMLParser.icc:31
#12 remollDetectorConstruction::ParseGDMLFile (this=0x560c582bb160) at /home/cde/mlrcd/src/remollDetectorConstruction.cc:544
#13 0x00007f0474460e85 in remollDetectorConstruction::Construct (this=0x560c582bb160) at /home/cde/mlrcd/src/remollDetectorConstruction.cc:912
#14 0x00007f047366653e in G4RunManager::InitializeGeometry() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#15 0x00007f04736662e4 in G4RunManager::Initialize() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#16 0x00007f047368420d in G4RunMessenger::SetNewValue(G4UIcommand*, G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4run.so
#17 0x00007f04735e335f in G4UIcommand::DoIt(G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#18 0x00007f0473600c9a in G4UImanager::ApplyCommand(char const*) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#19 0x00007f04735d1251 in G4UIbatch::ExecCommand(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#20 0x00007f04735d3206 in G4UIbatch::SessionStart() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#21 0x00007f0473602400 in G4UImanager::ExecuteMacroFile(char const*) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#22 0x00007f04735eed6d in G4UIcontrolMessenger::SetNewValue(G4UIcommand*, G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#23 0x00007f04735e335f in G4UIcommand::DoIt(G4String) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#24 0x00007f0473600c9a in G4UImanager::ApplyCommand(char const*) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4intercoms.so
#25 0x00007f0473abb89f in G4VBasicShell::ExecuteCommand(G4String const&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#26 0x00007f0473ac0ade in G4VBasicShell::ApplyShellCommand(G4String const&, bool&, bool&) () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#27 0x00007f0473ab08ae in G4UIQt::CommandEnteredCallback() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#28 0x00007f046e9bb300 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007f046f64d4a9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007f046e9bb300 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007f046f653c85 in QWidgetLineControl::processKeyEvent(QKeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007f046f64699f in QLineEdit::keyPressEvent(QKeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007f046f54377d in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007f046f64cd32 in QLineEdit::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007f046f500a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007f046f50a81e in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007f046e98f93a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007f046f562216 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007f046f500a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#40 0x00007f046f50a0f0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#41 0x00007f046e98f93a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007f046ed74b2b in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#43 0x00007f046ed7a0f1 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#44 0x00007f046ed5435b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#45 0x00007f045875a32e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#46 0x00007f046d2b317d in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#47 0x00007f046d2b3400 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007f046d2b34a3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007f046e9e7565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#50 0x00007f046e98e4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#51 0x00007f046e996246 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007f0473aac28d in G4UIQt::SessionStart() () from /home/cde/geant4/geant4.10.07.p01-install/lib/libG4interfaces.so
#53 0x0000560c54ae550a in main (argc=1, argv=0x7ffe53039a38) at /home/cde/mlrcd/remoll.cc:162
===========================================================


cde@cde-Latitude-E7250:~/mlrcd$ 
`
