### ISSUE TITLE
Segmentation fault when replaying large number of events (for example >100k)

### ISSUE THREAD

**Issue by hanjie1** [JeffersonLab/remoll#492]
### Environment: (where does this bug occur, have you tried other environments)
- branch (master for latest released): hanjie/remoll/feature-optics
- revision (HEAD for most recent):  2062747 (most recent version)

- OS or system: CentOS release 6.10
- Special ROOT or Geant4 versions? ROOT 6.14/06....geant4.10.04.p02

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. In "macros/runexample.mac": /run/beamOn 100000
2. /build/remoll macros/runexample.mac

### Expected Result: (what do you expect when you execute the steps above)
generate a root file
note: when using old field maps, no such segmentation faults.

### Actual Result: (what do you get when you execute the steps above)
```
 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 3 (Thread 0x7fe3fa052700 (LWP 14002)):
#0  0x00000037332ac8dd in waitpid () from /lib64/libc.so.6
#1  0x000000373323e4e9 in do_system () from /lib64/libc.so.6
#2  0x000000373323e820 in system () from /lib64/libc.so.6
#3  0x00007fe413834787 in Exec (shellcmd=<optimized out>, this=0x1737130) at /export/apps/root-6.14.06/core/unix/src/TUnixSystem.cxx:2119
#4  TUnixSystem::StackTrace (this=0x1737130) at /export/apps/root-6.14.06/core/unix/src/TUnixSystem.cxx:2413
#5  0x00007fe413836d94 in TUnixSystem::DispatchSignals (this=0x1737130, sig=kSigSegmentationViolation) at /export/apps/root-6.14.06/core/unix/src/TUnixSystem.cxx:3644
#6  <signal handler called>
#7  0x00007fe413c3250f in remollMagneticField::GetFieldValue (this=0x3eb0f00, Point=<optimized out>, Bfield=0x7fe3f9fe4ad0) at /home/hanjie/moller/remoll/src/remollMagneticField.cc:526
#8  0x00007fe413c27e77 in remollGlobalField::GetFieldValue (this=<optimized out>, p=0x7fe3f9fe4b30, resB=0x7fe3f9fe4bb0) at /home/hanjie/moller/remoll/src/remollGlobalField.cc:267
#9  0x00007fe4093ef0ec in GetFieldValue (this=<optimized out>, Field=0x7fe3f9fe4bb0, Point=0x7fe3f9fe4b30) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/include/G4EquationOfMotion.icc:55
#10 RightHandSide (dydx=0x7fe3f9fe4d10, y=0x7fe3f9fe4b50, this=0x7fe3f41415d0) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/include/G4EquationOfMotion.icc:73
#11 RightHandSide (this=0x7fe3f41416d0, this=0x7fe3f41416d0, dydx=0x7fe3f9fe4d10, y=0x7fe3f9fe4b50) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/include/G4MagIntegratorStepper.icc:60
#12 G4MagInt_Driver::GetDerivatives (this=<optimized out>, y_curr=..., dydx=0x7fe3f9fe4d10) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/src/G4MagIntegratorDriver.cc:1061
#13 0x00007fe4093da584 in G4ChordFinder::FindNextChord (this=0x7fe3f41418c0, yStart=..., stepMax=1000000, yEnd=..., dyErrPos=
0x7fe3f9fe4fd0: 1.7976931348623157e+308, epsStep=1.0000000000000001e-05, pStepForAccuracy=0x7fe3f9fe4fd8) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/src/G4ChordFinder.cc:414
#14 0x00007fe4093d8a3c in G4ChordFinder::AdvanceChordLimited (this=0x7fe3f41418c0, yCurrent=..., stepMax=stepMax
entry=1000000, epsStep=1.0000000000000001e-05, latestSafetyOrigin=..., latestSafetyRadius=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/src/G4ChordFinder.cc:358
#15 0x00007fe409459646 in G4PropagatorInField::ComputeStep (this=0x7fe3f404a830, pFieldTrack=..., CurrentProposedStepLength=1000000, CurrentProposedStepLength
entry=1.4985483763065747e+23, currentSafety=
0x7fe3f9fe5570: 0, pPhysVol=pPhysVol
entry=0x2ad7a90) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/src/G4PropagatorInField.cc:328
#16 0x00007fe40945203d in G4PathFinder::DoNextCurvedStep (this=this
entry=0x7fe3f418c800, initialState=..., proposedStepLength=proposedStepLength
entry=1.4985483763065747e+23, pCurrentPhysicalVolume=pCurrentPhysicalVolume
entry=0x2ad7a90) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/src/G4PathFinder.cc:1220
#17 0x00007fe409453816 in G4PathFinder::ComputeStep (this=0x7fe3f418c800, InitialFieldTrack=..., proposedStepLength=proposedStepLength
entry=1.4985483763065747e+23, navigatorNo=1, stepNo=47, pNewSafety=
0x7fe3f4417958: 2443.8404728703549, limitedStep=
0x7fe3f9fe5a3c: 1040264715, EndState=..., currentVolume=0x2ad7a90) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/src/G4PathFinder.cc:252
#18 0x00007fe40b614d39 in G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength (this=0x7fe3f4417590, track=..., previousStepSize=0.80677142057682494, currentMinimumStep=1.4985483763065747e+23, proposedSafety=
0x7fe3f9fe5aa8: 1.7976931348623157e+308, selection=0x7fe3f403c26c) at /share/apps/geant4/geant4.10.04.p02/source/processes/scoring/src/G4ParallelWorldProcess.cc:312
#19 0x00007fe40c2a5546 in AlongStepGPIL (selection=0x7fe3f403c26c, proposedSafety=
0x7fe3f9fe5aa8: 1.7976931348623157e+308, currentMinimumStep=<optimized out>, previousStepSize=<optimized out>, track=..., this=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/processes/management/include/G4VProcess.hh:489
#20 G4SteppingManager::DefinePhysicalStepLength (this=this
entry=0x7fe3f403c0e0) at /share/apps/geant4/geant4.10.04.p02/source/tracking/src/G4SteppingManager2.cc:246
#21 0x00007fe40c2a3660 in G4SteppingManager::Stepping (this=0x7fe3f403c0e0) at /share/apps/geant4/geant4.10.04.p02/source/tracking/src/G4SteppingManager.cc:180
#22 0x00007fe40c2af22c in G4TrackingManager::ProcessOneTrack (this=0x7fe3f403c0a0, apValueG4Track=apValueG4Track
entry=0x7fe3f4536410) at /share/apps/geant4/geant4.10.04.p02/source/tracking/src/G4TrackingManager.cc:126
#23 0x00007fe40c4e61b1 in G4EventManager::DoProcessing (this=0x7fe3f403c010, anEvent=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/event/src/G4EventManager.cc:185
#24 0x00007fe40c4e6bbc in G4EventManager::ProcessOneEvent (this=<optimized out>, anEvent=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/event/src/G4EventManager.cc:338
#25 0x00007fe40c78a92c in G4WorkerRunManager::ProcessOneEvent (this=0x7fe3f403bdc0, i_event=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4WorkerRunManager.cc:254
#26 0x00007fe40c78aaa9 in G4WorkerRunManager::DoEventLoop (this=0x7fe3f403bdc0, n_event=100000, macroFile=0x0, n_select=-1) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4WorkerRunManager.cc:232
#27 0x00007fe40c77d6be in G4RunManager::BeamOn (this=0x7fe3f403bdc0, n_event=100000, macroFile=0x0, n_select=-1) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4RunManager.cc:273
#28 0x00007fe40c78bac5 in G4WorkerRunManager::DoWork (this=0x7fe3f403bdc0) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4WorkerRunManager.cc:622
#29 0x00007fe40c796ebc in G4MTRunManagerKernel::StartThread (context=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4MTRunManagerKernel.cc:191
#30 0x00007fe40794eaa1 in start_thread () from /lib64/libpthread.so.0
#31 0x00000037332e8c4d in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fe3f9051700 (LWP 14003)):
#0  TransformPoint (vec=..., this=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/geometry/management/include/G4AffineTransform.icc:198
#1  ComputeLocalPoint (pGlobalPoint=..., this=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/include/G4Navigator.icc:69
#2  G4Navigator::ComputeSafety (this=0x7fe3ec419de0, pGlobalpoint=..., pMaxLength=1.7976931348623157e+308, keepState=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/src/G4Navigator.cc:1828
#3  0x00007fe409450931 in G4PathFinder::ComputeSafety (this=0x7fe3ec18b820, position=...) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/src/G4PathFinder.cc:767
#4  0x00007fe40945ffc8 in G4SafetyHelper::ComputeSafety (this=0x7fe3ec04e910, position=..., maxLength=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/src/G4SafetyHelper.cc:139
#5  0x00007fe40ae225f2 in ComputeSafety (this=0x7fe3ec1e1350, limit=<optimized out>, position=...) at /share/apps/geant4/geant4.10.04.p02/source/processes/electromagnetic/utils/include/G4VMscModel.hh:240
#6  G4UrbanMscModel::ComputeTruePathLengthLimit (this=0x7fe3ec1e1350, track=..., currentMinimalStep=
0x7fe3ec1df198: 0.16400163921047986) at /share/apps/geant4/geant4.10.04.p02/source/processes/electromagnetic/standard/src/G4UrbanMscModel.cc:604
#7  0x00007fe40ae8c70b in G4VMultipleScattering::AlongStepGetPhysicalInteractionLength (this=0x7fe3ec1def00, track=..., currentMinimalStep=<optimized out>, selection=0x7fe3ec03c2ac) at /share/apps/geant4/geant4.10.04.p02/source/processes/electromagnetic/utils/src/G4VMultipleScattering.cc:435
#8  0x00007fe40c2a5546 in AlongStepGPIL (selection=0x7fe3ec03c2ac, proposedSafety=
0x7fe3f8fe4aa8: 1.7976931348623157e+308, currentMinimumStep=<optimized out>, previousStepSize=<optimized out>, track=..., this=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/processes/management/include/G4VProcess.hh:489
#9  G4SteppingManager::DefinePhysicalStepLength (this=this
entry=0x7fe3ec03c120) at /share/apps/geant4/geant4.10.04.p02/source/tracking/src/G4SteppingManager2.cc:246
#10 0x00007fe40c2a3660 in G4SteppingManager::Stepping (this=0x7fe3ec03c120) at /share/apps/geant4/geant4.10.04.p02/source/tracking/src/G4SteppingManager.cc:180
#11 0x00007fe40c2af22c in G4TrackingManager::ProcessOneTrack (this=0x7fe3ec03c0e0, apValueG4Track=apValueG4Track
entry=0x7fe3ecc28df0) at /share/apps/geant4/geant4.10.04.p02/source/tracking/src/G4TrackingManager.cc:126
#12 0x00007fe40c4e61b1 in G4EventManager::DoProcessing (this=0x7fe3ec03c050, anEvent=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/event/src/G4EventManager.cc:185
#13 0x00007fe40c4e6bbc in G4EventManager::ProcessOneEvent (this=<optimized out>, anEvent=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/event/src/G4EventManager.cc:338
#14 0x00007fe40c78a92c in G4WorkerRunManager::ProcessOneEvent (this=0x7fe3ec03be00, i_event=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4WorkerRunManager.cc:254
#15 0x00007fe40c78aaa9 in G4WorkerRunManager::DoEventLoop (this=0x7fe3ec03be00, n_event=100000, macroFile=0x0, n_select=-1) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4WorkerRunManager.cc:232
#16 0x00007fe40c77d6be in G4RunManager::BeamOn (this=0x7fe3ec03be00, n_event=100000, macroFile=0x0, n_select=-1) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4RunManager.cc:273
#17 0x00007fe40c78bac5 in G4WorkerRunManager::DoWork (this=0x7fe3ec03be00) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4WorkerRunManager.cc:622
#18 0x00007fe40c796ebc in G4MTRunManagerKernel::StartThread (context=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4MTRunManagerKernel.cc:191
#19 0x00007fe40794eaa1 in start_thread () from /lib64/libpthread.so.0
#20 0x00000037332e8c4d in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fe4046a1580 (LWP 13980)):
#0  0x00007fe40795268c in pthread_cond_wait

GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007fe40897c1b3 in G4MTBarrier::Wait (this=0x2104bc8) at /share/apps/geant4/geant4.10.04.p02/source/global/management/src/G4MTBarrier.cc:92
#2  0x00007fe40c7851d1 in Wait (numt=<optimized out>, this=0x2104bc8) at /share/apps/geant4/geant4.10.04.p02/source/global/management/include/G4MTBarrier.hh:149
#3  G4MTRunManager::WaitForEndEventLoopWorkers (this=0x21049a0) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4MTRunManager.cc:585
#4  0x00007fe40c789c1d in G4MTRunManager::RunTermination (this=0x21049a0) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4MTRunManager.cc:383
#5  0x00007fe40c77d6c7 in G4RunManager::BeamOn (this=0x21049a0, n_event=100000, macroFile=0x0, n_select=-1) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4RunManager.cc:274
#6  0x00007fe40c798da9 in G4RunMessenger::SetNewValue (this=0x258ad40, command=command
entry=0x258b1e0, newValue=...) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4RunMessenger.cc:384
#7  0x00007fe408bbbaa5 in G4UIcommand::DoIt (this=this
entry=0x258b1e0, parameterList=...) at /share/apps/geant4/geant4.10.04.p02/source/intercoms/src/G4UIcommand.cc:233
#8  0x00007fe408bd754b in G4UImanager::ApplyCommand (this=0x16c1c10, aCmd=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/intercoms/src/G4UImanager.cc:530
#9  0x00007fe408bd8858 in G4UImanager::ApplyCommand (this=<optimized out>, aCmd=...) at /share/apps/geant4/geant4.10.04.p02/source/intercoms/src/G4UImanager.cc:447
#10 0x00007fe408baa92d in G4UIbatch::ExecCommand (this=this
entry=0x2882bb0, command=...) at /share/apps/geant4/geant4.10.04.p02/source/intercoms/src/G4UIbatch.cc:171
#11 0x00007fe408bac013 in G4UIbatch::SessionStart (this=0x2882bb0) at /share/apps/geant4/geant4.10.04.p02/source/intercoms/src/G4UIbatch.cc:216
#12 0x00007fe408bd0b83 in G4UImanager::ExecuteMacroFile (this=this
entry=0x16c1c10, fileName=0x2882728 "/home/hanjie/moller/remoll/macros/runexample.mac") at /share/apps/geant4/geant4.10.04.p02/source/intercoms/src/G4UImanager.cc:302
#13 0x0000000000407655 in main (argc=<optimized out>, argv=<optimized out>) at /home/hanjie/moller/remoll/remoll.cc:168
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#7  0x00007fe413c3250f in remollMagneticField::GetFieldValue (this=0x3eb0f00, Point=<optimized out>, Bfield=0x7fe3f9fe4ad0) at /home/hanjie/moller/remoll/src/remollMagneticField.cc:526
#8  0x00007fe413c27e77 in remollGlobalField::GetFieldValue (this=<optimized out>, p=0x7fe3f9fe4b30, resB=0x7fe3f9fe4bb0) at /home/hanjie/moller/remoll/src/remollGlobalField.cc:267
#9  0x00007fe4093ef0ec in GetFieldValue (this=<optimized out>, Field=0x7fe3f9fe4bb0, Point=0x7fe3f9fe4b30) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/include/G4EquationOfMotion.icc:55
#10 RightHandSide (dydx=0x7fe3f9fe4d10, y=0x7fe3f9fe4b50, this=0x7fe3f41415d0) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/include/G4EquationOfMotion.icc:73
#11 RightHandSide (this=0x7fe3f41416d0, this=0x7fe3f41416d0, dydx=0x7fe3f9fe4d10, y=0x7fe3f9fe4b50) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/include/G4MagIntegratorStepper.icc:60
#12 G4MagInt_Driver::GetDerivatives (this=<optimized out>, y_curr=..., dydx=0x7fe3f9fe4d10) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/src/G4MagIntegratorDriver.cc:1061
#13 0x00007fe4093da584 in G4ChordFinder::FindNextChord (this=0x7fe3f41418c0, yStart=..., stepMax=1000000, yEnd=..., dyErrPos=
0x7fe3f9fe4fd0: 1.7976931348623157e+308, epsStep=1.0000000000000001e-05, pStepForAccuracy=0x7fe3f9fe4fd8) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/src/G4ChordFinder.cc:414
#14 0x00007fe4093d8a3c in G4ChordFinder::AdvanceChordLimited (this=0x7fe3f41418c0, yCurrent=..., stepMax=stepMax
entry=1000000, epsStep=1.0000000000000001e-05, latestSafetyOrigin=..., latestSafetyRadius=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/geometry/magneticfield/src/G4ChordFinder.cc:358
#15 0x00007fe409459646 in G4PropagatorInField::ComputeStep (this=0x7fe3f404a830, pFieldTrack=..., CurrentProposedStepLength=1000000, CurrentProposedStepLength
entry=1.4985483763065747e+23, currentSafety=
0x7fe3f9fe5570: 0, pPhysVol=pPhysVol
entry=0x2ad7a90) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/src/G4PropagatorInField.cc:328
#16 0x00007fe40945203d in G4PathFinder::DoNextCurvedStep (this=this
entry=0x7fe3f418c800, initialState=..., proposedStepLength=proposedStepLength
entry=1.4985483763065747e+23, pCurrentPhysicalVolume=pCurrentPhysicalVolume
entry=0x2ad7a90) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/src/G4PathFinder.cc:1220
#17 0x00007fe409453816 in G4PathFinder::ComputeStep (this=0x7fe3f418c800, InitialFieldTrack=..., proposedStepLength=proposedStepLength
entry=1.4985483763065747e+23, navigatorNo=1, stepNo=47, pNewSafety=
0x7fe3f4417958: 2443.8404728703549, limitedStep=
0x7fe3f9fe5a3c: 1040264715, EndState=..., currentVolume=0x2ad7a90) at /share/apps/geant4/geant4.10.04.p02/source/geometry/navigation/src/G4PathFinder.cc:252
#18 0x00007fe40b614d39 in G4ParallelWorldProcess::AlongStepGetPhysicalInteractionLength (this=0x7fe3f4417590, track=..., previousStepSize=0.80677142057682494, currentMinimumStep=1.4985483763065747e+23, proposedSafety=
0x7fe3f9fe5aa8: 1.7976931348623157e+308, selection=0x7fe3f403c26c) at /share/apps/geant4/geant4.10.04.p02/source/processes/scoring/src/G4ParallelWorldProcess.cc:312
#19 0x00007fe40c2a5546 in AlongStepGPIL (selection=0x7fe3f403c26c, proposedSafety=
0x7fe3f9fe5aa8: 1.7976931348623157e+308, currentMinimumStep=<optimized out>, previousStepSize=<optimized out>, track=..., this=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/processes/management/include/G4VProcess.hh:489
#20 G4SteppingManager::DefinePhysicalStepLength (this=this
entry=0x7fe3f403c0e0) at /share/apps/geant4/geant4.10.04.p02/source/tracking/src/G4SteppingManager2.cc:246
#21 0x00007fe40c2a3660 in G4SteppingManager::Stepping (this=0x7fe3f403c0e0) at /share/apps/geant4/geant4.10.04.p02/source/tracking/src/G4SteppingManager.cc:180
#22 0x00007fe40c2af22c in G4TrackingManager::ProcessOneTrack (this=0x7fe3f403c0a0, apValueG4Track=apValueG4Track
entry=0x7fe3f4536410) at /share/apps/geant4/geant4.10.04.p02/source/tracking/src/G4TrackingManager.cc:126
#23 0x00007fe40c4e61b1 in G4EventManager::DoProcessing (this=0x7fe3f403c010, anEvent=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/event/src/G4EventManager.cc:185
#24 0x00007fe40c4e6bbc in G4EventManager::ProcessOneEvent (this=<optimized out>, anEvent=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/event/src/G4EventManager.cc:338
#25 0x00007fe40c78a92c in G4WorkerRunManager::ProcessOneEvent (this=0x7fe3f403bdc0, i_event=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4WorkerRunManager.cc:254
#26 0x00007fe40c78aaa9 in G4WorkerRunManager::DoEventLoop (this=0x7fe3f403bdc0, n_event=100000, macroFile=0x0, n_select=-1) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4WorkerRunManager.cc:232
#27 0x00007fe40c77d6be in G4RunManager::BeamOn (this=0x7fe3f403bdc0, n_event=100000, macroFile=0x0, n_select=-1) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4RunManager.cc:273
#28 0x00007fe40c78bac5 in G4WorkerRunManager::DoWork (this=0x7fe3f403bdc0) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4WorkerRunManager.cc:622
#29 0x00007fe40c796ebc in G4MTRunManagerKernel::StartThread (context=<optimized out>) at /share/apps/geant4/geant4.10.04.p02/source/run/src/G4MTRunManagerKernel.cc:191
#30 0x00007fe40794eaa1 in start_thread () from /lib64/libpthread.so.0
#31 0x00000037332e8c4d in clone () from /lib64/libc.so.6

===========================================================



 *** Break *** segmentation violation

```

**Comment by wdconinc** [comment]
Can you reproduce this on develop? What is the difference between hanjie/remoll/feature-optics and develop? When was the last time (as hash) when you merged changes from develop into hanjie/remoll/feature-optics?

**Comment by hanjie1** [comment]
I think the main difference is that "hanjie/remoll/feature-optics" includes the target ladder changes and the multi-scattering changes in "feature-target-ladder". So I couldn't merge with develop. The last time I merged from develop should be early January.

**Comment by hanjie1** [comment]
It's fixed by implementing this fix: 
https://github.com/JeffersonLab/remoll/pull/456
