### ISSUE TITLE
remollGenPion crashes in multithreading due to TF1

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/remoll#88]
```
#6  0x00007f5fd318cbfd in TList::Remove (this=0x565551d59ba0, obj=<optimized out>) at /usr/local/src/root/root-6.10.08/core/cont/src/TList.cxx:704
#7  0x00007f5fd16188aa in TF1::DoInitialize (this=0x7f5fae434440, addToGlobalList=<optimized out>) at /usr/local/src/root/root-6.10.08/hist/hist/src/TF1.cxx:632
#8  0x00007f5fd1621bc6 in TF1::TF1 (this=0x7f5fae434440, name=<optimized out>, fcn=<optimized out>, xmin=<optimized out>, xmax=<optimized out>, npar=<optimized out>, ndim=<optimized out>, addToGlobList=TF1::EAddToList::kDefault) at /usr/local/src/root/root-6.10.08/hist/hist/src/TF1.cxx:544
#9  0x00007f5fd5cd5407 in remollGenPion::wiser_sigma (this=this
entry=0x7f5fac0e69f0, Ebeam=Ebeam
entry=8.2105061783679769, pf=pf
entry=3.871373929852207, thf=thf
entry=0.012328466502100097, rad_len=rad_len
entry=0.18687514790068088, type=type
entry=0) at /home/wdconinc/git/remoll/src/remollGenPion.cc:233
#10 0x00007f5fd5cd5a58 in remollGenPion::SamplePhysics (this=0x7f5fac0e69f0, vert=0x7f5fb3988890, evt=0x7f5fadfd7700) at /home/wdconinc/git/remoll/src/remollGenPion.cc:73
```

**Comment by wdconinc** [comment]
Branch bugfix_issue_88

**Comment by wdconinc** [comment]
Branch bugfix_issue_88 deleted.
